FROM node:20-slim

# Install Firebase CLI
RUN npm install -g firebase-tools

# Install Java for Firestore Emulator
RUN apt-get update && apt-get install -y default-jre

# Set working directory
WORKDIR /app

# Optional: expose default emulator ports
EXPOSE 8085
EXPOSE 4000
